# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: v2
name: hcp-terraform-operator
description: Official Helm chart for HCP Terraform Operator for Kubernetes.
type: application
version: "2.7.1"
appVersion: "2.7.1"
