# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

## Append samples you want in your CSV to this file as resources ##
resources:
- app_v1alpha2_workspace.yaml
- app_v1alpha2_module.yaml
- app_v1alpha2_agentpool.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
