# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "terraform-cloud-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}