# Copyright IBM Corp. 2022, 2025
# SPDX-License-Identifier: MPL-2.0

# Configuration file for CRD Reference Documentation Generator: https://github.com/elastic/crd-ref-docs
processor:
  ignoreTypes:
    - "AgentPoolList$"
    - "AgentTokenList$"
    - "ModuleList$"
    - "ProjectList$"
    - "RunsCollectorList$"
    - "WorkspaceList$"
  ignoreFields:
    - "status$"
render:
  kubernetesVersion: 1.32
