name: "IBM Copywrite"

on:
  schedule:
    - cron: '30 2 * * *'
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  copywrite:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

    - name: Install copywrite
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make install-copywrite

    - name: Generate copywrite headers
      run: make copywrite

    - name: Validate changes
      run: git diff --exit-code

    - name: Missing or incorrect headers
      if: ${{ failure() }}
      run: |
        echo "There are files with missing or incorrect copywrite headers. Please run 'make copywrite'."
        exit 1

    - name: Green light
      if:   ${{ success() }}
      run: |
        echo "All files have correct copywrite headers."
        exit 0
