name: Intergation tests

on:
  workflow_dispatch:
    inputs:
      concurrentRuns:
        description: Number of concurrent runs
        default: "5"

env:
  TFC_ORG: ${{ secrets.TFC_ORG }}
  TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
  TFC_OAUTH_TOKEN: ${{ secrets.TFC_OAUTH_TOKEN }}
  TFC_VCS_REPO: ${{ secrets.TFC_VCS_REPO }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo
      - name: Run integration test suite
        env:
          GINKGO_CONCURRENT_RUNS: ${{ github.event.inputs.concurrentRuns }}
        run: make ginkgo-test
