# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: v2
name: terraform-cloud-operator
description: Official Helm chart for HCP Terraform Operator for Kubernetes.
type: application
version: "2.4.0"
appVersion: "2.4.0"
