# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: v2
name: terraform-cloud-operator
description: A Helm chart for HashiCorp Terraform Cloud Kubernetes Operator.
type: application
version: 0.0.7
appVersion: "2.0.0-beta6"
