# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: v2
name: terraform-cloud-operator
description: Official Helm chart for HashiCorp Terraform Cloud Kubernetes Operator.
type: application
version: 2.0.0-beta7
appVersion: 2.0.0-beta7
